ci: default run ci on ARM64 runner

diff --git a/.github/workflows/reuse.linux.yml b/.github/workflows/reuse.linux.yml
--- a/.github/workflows/reuse.linux.yml
+++ b/.github/workflows/reuse.linux.yml
@@ -13,6 +13,11 @@ on:
         type: string
         required: true
         default: "aws"
+      runner_arch:
+        description: "Runner architecture, X64 or ARM64"
+        type: string
+        required: true
+        default: "X64"
       license_type:
         description: "License type, enterprise or trial"
         type: string
@@ -27,7 +32,7 @@ jobs:
   check:
     runs-on:
       - self-hosted
-      - X64
+      - "${{ inputs.runner_arch }}"
       - Linux
       - 8c32g
       - "${{ inputs.runner_provider }}"
@@ -44,21 +49,26 @@ jobs:
   build:
     runs-on:
       - self-hosted
-      - "${{ matrix.runner }}"
+      - "${{ inputs.runner_arch }}"
       - Linux
       - 16c64g
       - "${{ inputs.runner_provider }}"
-    strategy:
-      fail-fast: false
-      matrix:
-        include:
-          - { arch: x86_64, runner: X64 }
-          # - { arch: aarch64, runner: ARM64 }
     steps:
       - uses: actions/checkout@v4
         with:
           # fetch all tags, metasrv and meta client need tag as its version.
           fetch-depth: 0
+      - name: Get build target
+        id: target
+        run: |
+          if [ "${{ inputs.runner_arch }}" == "X64" ]; then
+            echo "target=x86_64-unknown-linux-gnu" >> $GITHUB_OUTPUT
+          elif [ "${{ inputs.runner_arch }}" == "ARM64" ]; then
+            echo "target=aarch64-unknown-linux-gnu" >> $GITHUB_OUTPUT
+          else
+            echo "Invalid runner architecture: ${{ inputs.runner_arch }}"
+            exit 1
+          fi
       - uses: ./.github/actions/build_linux
         timeout-minutes: 60
         env:
@@ -67,7 +77,7 @@ jobs:
           DATABEND_TELEMETRY_API_KEY: ${{ secrets.DATABEND_TELEMETRY_API_KEY}}
         with:
           sha: ${{ github.sha }}
-          target: ${{ matrix.arch }}-unknown-linux-gnu
+          target: ${{ steps.target.outputs.target }}
           features: python-udf,storage-hdfs
           category: full
           artifacts: all
@@ -75,36 +85,13 @@ jobs:
         if: always()
         uses: actions/upload-artifact@v4
         with:
-          name: sccache-build-${{ matrix.arch }}
+          name: sccache-build-${{ steps.target.outputs.target }}
           path: target/sccache.log
-
-  # build_address_sanitizer:
-  #   runs-on:
-  #     - self-hosted
-  #     - "${{ matrix.runner }}"
-  #     - Linux
-  #     - 8c32g
-  #     - "${{ inputs.runner_provider }}"
-  #   strategy:
-  #     fail-fast: false
-  #     matrix:
-  #       include:
-  #         - { arch: aarch64, runner: ARM64 }
-  #   steps:
-  #     - uses: actions/checkout@v4
-  #       with:
-  #         # fetch all tags, metasrv and metaclient need tag as its version.
-  #         fetch-depth: 0
-  #     - uses: ./.github/actions/build_linux_sanitizer
-  #       timeout-minutes: 60
-  #       with:
-  #         target: ${{ matrix.arch }}-unknown-linux-gnu
-  #         artifacts: query
 
   test_unit:
     runs-on:
       - self-hosted
-      - X64
+      - "${{ inputs.runner_arch }}"
       - Linux
       - 16c64g
       - "${{ inputs.runner_provider }}"
@@ -120,7 +107,7 @@ jobs:
     needs: [ build, check ]
     runs-on:
       - self-hosted
-      - X64
+      - "${{ inputs.runner_arch }}"
       - Linux
       - 2c8g
       - "${{ inputs.runner_provider }}"
@@ -133,7 +120,7 @@ jobs:
     needs: [ build, check ]
     runs-on:
       - self-hosted
-      - X64
+      - "${{ inputs.runner_arch }}"
       - Linux
       - 2c8g
       - "${{ inputs.runner_provider }}"
@@ -146,7 +133,7 @@ jobs:
     needs: [ build, check ]
     runs-on:
       - self-hosted
-      - X64
+      - "${{ inputs.runner_arch }}"
       - Linux
       - 2c8g
       - "${{ inputs.runner_provider }}"
@@ -159,7 +146,7 @@ jobs:
     needs: [ build, check ]
     runs-on:
       - self-hosted
-      - X64
+      - "${{ inputs.runner_arch }}"
       - Linux
       - 2c8g
       - "${{ inputs.runner_provider }}"
@@ -172,7 +159,7 @@ jobs:
     needs: [ build, check ]
     runs-on:
       - self-hosted
-      - X64
+      - "${{ inputs.runner_arch }}"
       - Linux
       - 2c8g
       - "${{ inputs.runner_provider }}"
@@ -189,7 +176,7 @@ jobs:
     needs: [ build, check ]
     runs-on:
       - self-hosted
-      - X64
+      - "${{ inputs.runner_arch }}"
       - Linux
       - 8c32g
       - "${{ inputs.runner_provider }}"
@@ -206,7 +193,7 @@ jobs:
     needs: [ build, check ]
     runs-on:
       - self-hosted
-      - X64
+      - "${{ inputs.runner_arch }}"
       - Linux
       - 2c8g
       - "${{ inputs.runner_provider }}"
@@ -219,7 +206,7 @@ jobs:
     needs: [ build, check ]
     runs-on:
       - self-hosted
-      - X64
+      - "${{ inputs.runner_arch }}"
       - Linux
       - 2c8g
       - "${{ inputs.runner_provider }}"
@@ -232,7 +219,7 @@ jobs:
     needs: [ build, check ]
     runs-on:
       - self-hosted
-      - X64
+      - "${{ inputs.runner_arch }}"
       - Linux
       - 2c8g
       - "${{ inputs.runner_provider }}"
@@ -249,7 +236,7 @@ jobs:
     needs: [ build, check ]
     runs-on:
       - self-hosted
-      - X64
+      - "${{ inputs.runner_arch }}"
       - Linux
       - 2c8g
       - "${{ inputs.runner_provider }}"
@@ -267,7 +254,7 @@ jobs:
     needs: [ build, check ]
     runs-on:
       - self-hosted
-      - X64
+      - "${{ inputs.runner_arch }}"
       - Linux
       - 2c8g
       - "${{ inputs.runner_provider }}"
@@ -290,7 +277,7 @@ jobs:
     needs: [ build, check ]
     runs-on:
       - self-hosted
-      - X64
+      - "${{ inputs.runner_arch }}"
       - Linux
       - 2c8g
       - "${{ inputs.runner_provider }}"
@@ -303,7 +290,7 @@ jobs:
     needs: [ build, check ]
     runs-on:
       - self-hosted
-      - X64
+      - "${{ inputs.runner_arch }}"
       - Linux
       - 2c8g
       - "${{ inputs.runner_provider }}"
@@ -321,7 +308,7 @@ jobs:
     needs: [ build, check ]
     runs-on:
       - self-hosted
-      - X64
+      - "${{ inputs.runner_arch }}"
       - Linux
       - 2c8g
       - "${{ inputs.runner_provider }}"
@@ -339,7 +326,7 @@ jobs:
   #   needs: [build, check]
   #   runs-on:
   #     - self-hosted
-  #     - X64
+  #     - "${{ inputs.runner_arch }}"
   #     - Linux
   #     - 2c8g
   #     - "${{ inputs.runner_provider }}"
@@ -353,7 +340,7 @@ jobs:
     needs: [ build, check ]
     runs-on:
       - self-hosted
-      - X64
+      - "${{ inputs.runner_arch }}"
       - Linux
       - 2c8g
       - "${{ inputs.runner_provider }}"
@@ -380,7 +367,7 @@ jobs:
   #    needs: [build, check]
   #    runs-on:
   #      - self-hosted
-  #      - X64
+  #      - "${{ inputs.runner_arch }}"
   #      - Linux
   #      - 2c8g
   #      - "${{ inputs.runner_provider }}"
@@ -402,7 +389,7 @@ jobs:
     needs: [ build, check ]
     runs-on:
       - self-hosted
-      - X64
+      - "${{ inputs.runner_arch }}"
       - Linux
       - 2c8g
       - "${{ inputs.runner_provider }}"
@@ -428,4 +415,5 @@ jobs:
     with:
       build_profile: ${{ inputs.build_profile }}
       runner_provider: ${{ inputs.runner_provider }}
+      runner_arch: ${{ inputs.runner_arch }}
       license_type: ${{ inputs.license_type }}
